---
name: checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"

